GET http://localhost:80/api/item?id=99
Accept: application/json

###
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client#environment-variables

### 

@host = localhost
@port = 8888




### 
# 添加域名
POST http://{{host}}:{{port}}/domain HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=www.360.cn
